#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "n32g45x.h"

#define BOARD_AFE_SCL_PORT        GPIOD
#define BOARD_AFE_SCL_PIN         GPIO_PIN_1

#define BOARD_AFE_SDA_PORT        GPIOD
#define BOARD_AFE_SDA_PIN         GPIO_PIN_2

#define BOARD_AFE_NSHDN_PORT      GPIOC
#define BOARD_AFE_NSHDN_PIN       GPIO_PIN_3

#define BOARD_AFE_XALERT_PORT     GPIOD
#define BOARD_AFE_XALERT_PIN      GPIO_PIN_10
#define BOARD_AFE_XALERT_PRESENT  0

#define BOARD_POWER_CTRL1_PORT    GPIOB
#define BOARD_POWER_CTRL1_PIN     GPIO_PIN_12

#define BOARD_POWER_CTRL2_PORT    GPIOB
#define BOARD_POWER_CTRL2_PIN     GPIO_PIN_13

/* U101：单体 1～8 的 SGM4518 地址线。 */
#define BOARD_BALANCE_LOW_A_PORT  GPIOC
#define BOARD_BALANCE_LOW_A_PIN   GPIO_PIN_6
#define BOARD_BALANCE_LOW_B_PORT  GPIOD
#define BOARD_BALANCE_LOW_B_PIN   GPIO_PIN_9
#define BOARD_BALANCE_LOW_C_PORT  GPIOD
#define BOARD_BALANCE_LOW_C_PIN   GPIO_PIN_8

/* U100：单体 9～16 的 SGM4518 地址线。 */
#define BOARD_BALANCE_HIGH_A_PORT GPIOA
#define BOARD_BALANCE_HIGH_A_PIN  GPIO_PIN_8
#define BOARD_BALANCE_HIGH_B_PORT GPIOC
#define BOARD_BALANCE_HIGH_B_PIN  GPIO_PIN_9
#define BOARD_BALANCE_HIGH_C_PORT GPIOC
#define BOARD_BALANCE_HIGH_C_PIN  GPIO_PIN_8

/* 两片 SGM4518 共用的低有效选通脚。 */
#define BOARD_BALANCE_MUX_EN_PORT GPIOC
#define BOARD_BALANCE_MUX_EN_PIN  GPIO_PIN_7

/* U104、U105 电源级使能，高电平启动对应的 ME8320。 */
#define BOARD_BALANCE_LOW_PWR_PORT  GPIOA
#define BOARD_BALANCE_LOW_PWR_PIN   GPIO_PIN_6
#define BOARD_BALANCE_HIGH_PWR_PORT GPIOB
#define BOARD_BALANCE_HIGH_PWR_PIN  GPIO_PIN_1

/*
 * 隔离RS232接口：U45-68=PA9/USART1_TX，U45-69=PA10/USART1_RX。
 * GPIO复用和USART参数由NTFx生成代码负责配置。
 */
#define BOARD_RS232_USART USART1

/* PC10/PC11 调试串口，外设及引脚复用由 NTFx 生成代码配置。 */
#define BOARD_PC_UART UART4

#endif /* BOARD_PINS_H */
